out: /cmap/chicory/daemon/utils/my_analysis.sig_gutc_tool.5c33e507b306063b135bfc88
runtests: false
rundemo: false
rpt: BT084
create_subdir: false
verbose: true
encode_url: false
config: http://data.clue.io/api/ejuarez@cloud.ucsd.edu/results/Jan_07_2019/my_analysis.sig_gutc_tool.5c33e507b306063b135bfc88/config.yaml
query_result: []
up: http://data.clue.io/api/ejuarez%40cloud.ucsd.edu/results/Jan_07_2019/my_analysis.sig_gutc_tool.5c33e507b306063b135bfc88/uptag.gmt
down: http://data.clue.io/api/ejuarez%40cloud.ucsd.edu/results/Jan_07_2019/my_analysis.sig_gutc_tool.5c33e507b306063b135bfc88/dntag.gmt
query_meta: []
is_matched: false
match_group: pert_id,pert_idose,pert_itime
metric: wtcs
es_tail: up
rank: []
score: []
build_id: a2geneid
feature_space: bing
sample_space: full
pcl_set: /cmap/data/vdb/touchstone_v1.1/matched/annot/pcl_n171_20170201.gmt
bkg_path: /cmap/data/vdb/touchstone_v1.1/matched
save_matrices: true
save_digests: true
undef_action: warn
